---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup HIV-Pr for docking study

```{r}
library(bio3d)
```


Get the protein first (ie download)
```{r}
file.name <-  get.pdb("1hsg")


```


Read this file in and trim out the protein, small molecule ligand from everything else

```{r}
hiv <- read.pdb(file.name)


```


```{r}
ligand <- trim.pdb(hiv, "ligand")
ligand
```


Extract protein

```{r}
protein <- trim.pdb(hiv, "protein")
protein
```

```{r}
write.pdb(ligand, "1hsg_ligand.pdb")
write.pdb(protein, "1hsg_protein.pdb")
```


## Process docking results for viewing in VMD

```{r}
library(bio3d)

res <-read.pdb("all.pdbqt", multi=TRUE)

write.pdb(res, "results.pdb")
```

```{r}


res <-read.pdb("all.pdbqt", multi=TRUE)

ori <-read.pdb("1hsg_ligand.pdbqt")

rmsd(ori, res)

```





```{r}
aa <-get.seq("P69441")
```

```{r}
b <-blast.pdb(aa)
```


```{r}
hits <-plot(b)
```


```{r}
head(hits$pdb.id)
```



```{r}
files <-get.pdb(hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```


```{r}
pdbs <-pdbaln(files, fit=TRUE)
```



```{r}
# Perform PCA & plot the results
pc.xray <-pca(pdbs)

plot(pc.xray)
```




```{r}
# Calculate RMSD
rd <-rmsd(pdbs)

# Structure-based clustering
hc.rd <-hclust(dist(rd))
grps.rd <-cutree(hc.rd, k=3)
```

```{r}
plot(pc.xray, 1:2, col="grey50", bg=grps.rd, pch=21, cex=1)
```





