---
title: "map_colors_function"
author: "Goya"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Let's look at the poor old function

This is the function code from Barry's student

```{r}
# Old function
map.colors <- function (value,high.low,palette) {
  proportion <- ((value-high.low[1])/(high.low[2]-high.low[1]))
  index <- round ((length(palette)-1)*proportion)+1
  return (palette[index])
}
```

Now lets try to understand this function...

```{r}
map.colors2 <- function (x, 
                         high.low = range(x), palette = cm.colors(100)) {
  
  # Determine where in the 'high.low' range our values of 'x' lie
  percent <- ((x - high.low[1])/(high.low[2] - high.low[1]))
  
  # Where in the 'palette' vector of colors is this 'percent'
  index <- round ( (length(palette) - 1) * percent) + 1
  
  return (palette[index])
}
```


## Working on my own functions
```{r}
add <- function(x, y=1) {  
    # Sum the input x and y
    x + y
}

```

Let's test our first function

```{r}
add(9)
```

```{r}
add(c(1:5), 20)
```

Does this work
```{r}
#add(1,3,10)
```

Write 2nd function

```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

Test my 2nd function
```{r}
rescale(c(1,2,NA,3,10))
```

Rescale 2
```{r}
rescale2 <- function(x) {
   rng <-range(x, na.rm=TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

Rescale 3
```{r}
rescale3 <- 
function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")
   
   answer <-(x - rng[1]) / (rng[2] - rng[1])
   
  
   
   print("is it me you are looking for?")
   if(plot) { 
      plot(answer, typ="b", lwd=4) 
   }
   print("I can see it in ...")
   return(answer)
}
```

```{r}
rescale3(c(1,2,NA,3,10), plot = TRUE)
```





## Section 2B from Class 6

```{r}
library(bio3d)

```

Make this code simpler

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor") 
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```




```{r}
goya <- function(x) {
  
# First retrive PDB file, define as vector v
  v <- read.pdb(x)
  
# Then trim it, selecting only chain A, alpha carbons
  v.chainA <- trim.pdb(v, chain = "A", elety = "CA")
  
# Next, define vector of only B-values for the trimmed vector
  
  v.b <- v.chainA$atom$b
  
# Finally, plot the B-factor vs. residue
  
  plotb3(v.b, sse = v.chainA, typ = "1", ylab ="B-factor")
  
}

goya("4AKE")
```





